### ISSUE TITLE
Could you share the principle of the cracking?

### ISSUE THREAD

**Issue by phoenixsfly** [winderica/ChuangGaoFucker#2]
It seems very complicated to use...
I would rather using Xposed to change GPS data...
So could you share the principle of the cracking and we will help you to make the program easier to use.

**Comment by winderica** [comment]
关于原理，现在已经在写了，稍加整理之后就会给出。
这几天一直在寻找易用的解决方案，但是仍然处于想法阶段。确实root+frida对大多数人来说门槛较高，不过由于该应用的请求header中部分参数由so库进行hash/加密，自己反汇编能力不足，直接寻找加密方法较为困难，断绝了[这个仓库](https://github.com/Letra312/chuanggao-checkIn)中直接POST数据的可能性，只好暂时使用目前的解决方案。
xposed改GPS可行，但是有以下缺陷：
1. 该应用上传的数据中有步数（之后可能会作为考核依据）
2. 过一会就改个GPS感觉也挺繁琐的，不知道你怎么看？

**Comment by ManiaciaChao** [comment]
步数一般是加速度传感器，这个通过xposed也很容易操作。

**Comment by winderica** [comment]
如果可以的话，也欢迎留下你的联系方式，以便进一步讨论。

**Comment by phoenixsfly** [comment]
对了，能否给出一个在模拟器运行的方案？现在除了MIUI开发版自带root权限，其余手机尤其是华为，root极其困难。或者进一步直接做一个Android docker，自动化部署，不就很方便啦😁

**Comment by winderica** [comment]
1. 现在的Android模拟器基本上都是x86的，arm的速度极慢，然而该应用只提供了arm64的so库，虽然有相应的解决方案，不过基本无效。
2. 关于部分机型无法root的问题，目前无解。
3. 至于docker，我持保留意见。容器化是好事，但是并不是什么都适合容器化。对于真的**什么都不懂**的人来说，个人认为上手root比上手docker要方便，况且docker下还是需要用frida，不会降低复杂度。当然，如果你有相应的想法，也欢迎提交pr

**Comment by user7z1w40** [comment]
你可以参考[Exposed](https://github.com/android-hacker/exposed)。非root权限可能会有帮助。

**Comment by winderica** [comment]
用Exposed的话就要用Java来hook了，然而我并不是Java选手（

**Comment by featherin** [comment]
Close due to inactivity.
