### ISSUE TITLE
It do not work on my phone

### ISSUE THREAD

**Issue by MacsedProtoss** [winderica/ChuangGaoFucker#3]
The application **stays unresponsive** with a white screen.
Platform: XiaoMi Mix2S [polaris] 
System: MIUI global 10.2(stable)
Android Version : 9.0

In terminal , it shows like this 

` [Xiaomi MIX 2S::net.crigh.cgsport]-> Process terminated`

**Comment by winderica** [comment]
注释掉hook.js的[第407行](https://github.com/featherin/ChuangGaoFucker/blob/294129a30a39b1c3630580f7a521b5c92e1b06e7/hooks.js#L407)试试？

**Comment by MacsedProtoss** [comment]
> 注释掉hook.js的[第407行](https://github.com/featherin/ChuangGaoFucker/blob/294129a30a39b1c3630580f7a521b5c92e1b06e7/hooks.js#L407)试试？

Then it stuck in main screen & in terminal it shows `[Xiaomi MIX 2S::net.crigh.cgsport]->`

**Comment by MacsedProtoss** [comment]
Then I manually get into the running page .
And it works awesome

**Comment by MacsedProtoss** [comment]
So If someone get into the same trouble, please commit the 407th line in hook.js & manually get into run page

**Comment by winderica** [comment]
~~我的环境是：~~
* ~~红米note 3~~
* ~~Linageos 14.1 (Android 7.1)~~
* ~~创高版本2.5.9~~

~~开始确实会白屏一小会，不过正常运行，不知道是不是系统的原因？~~
~~可以输`adb logcat`看看~~
我往readme里append一下吧

**Comment by MacsedProtoss** [comment]
Though it works , there is a bug .
In my records, The total exercise is 3.12 kilometers with 1 verified run count.
But while tapping into the detailed records， it shows 0.0 kilometers .

As for the result of adb logcat | grep net.crigh.cgsport , it shows a error in network before commiting 407th line.

**Comment by winderica** [comment]
停止frida-server后，锻炼详情是正常的吗？

**Comment by MacsedProtoss** [comment]
> 停止frida-server后，锻炼详情是正常的吗？

nope. Nothing changed.

**Comment by winderica** [comment]
试了几次都没有复现，就你的情况来看可能是在hook过程中有欠缺的地方，有空会跟进一下

**Comment by winderica** [comment]
明白为什么了。
它本地有个数据库，我在hook过程中只修改了getter，因此本地的数据仍然是0公里。
如果清除该应用的数据、缓存再次打开，数据应该会恢复正常。
这样确实挺麻烦的，之后会再看看它的源码。

**Comment by featherin** [comment]
Close due to inactivity.
