### ISSUE TITLE
Problem about using frida-gadgets

### ISSUE THREAD

**Issue by 78ij** [winderica/ChuangGaoFucker#4]
Using frida-gadgets requires the user to re-package the apk, which will change the certification of the apk. Unfortunately, the AMap (Gaode) API requires the SHA1 code of the apk to verify. This means the re-package method may not be avaliable.

**Comment by winderica** [comment]
最初xxx跟我说起这个的时候我觉得可行，所以加到了TODO里。
实际上，不考虑API验证的问题，由于乐固壳的存在，frida-gadgets根本不能对它重新打包。
现在我们在尝试写一个app，直接调用它so库中的加密函数来发送数据。

**Comment by 78ij** [comment]
> 最初xxx跟我说起这个的时候我觉得可行，所以加到了TODO里。
> 实际上，不考虑API验证的问题，由于乐固壳的存在，frida-gadgets根本不能对它重新打包。
> 现在我们在尝试写一个app，直接调用它so库中的加密函数来发送数据。

看来只能如此...
