### ISSUE TITLE
Error: access violation accessing 0x8

### ISSUE THREAD

**Issue by linseedence** [winderica/ChuangGaoFucker#5]
![image](https://user-images.githubusercontent.com/48386133/54083416-e08f0680-435d-11e9-8f09-7e85b8164d26.png)
你好，请问一下大大，出现这样的错误是怎么回事呢，是frida的版本不对么。
Frida version: 12.4.0 Android arm64
Androidversion: Android 9.0.0
Device: sony xzpremium
已root，frida-sever运行正常，使用命令frida-ps -U，能够打印出进程列表，运行前已清除cgsport的数据
麻烦大大了。

**Comment by winderica** [comment]
找了一下frida的issue，大概是系统版本的问题。试试在`hook.js`中注释掉[第407行](https://github.com/featherin/ChuangGaoFucker/blob/294129a30a39b1c3630580f7a521b5c92e1b06e7/hooks.js#L407)？

**Comment by linseedence** [comment]
嗯嗯已经尝试注释过了不过还是同样的问题。。。是安卓版本的原因么。。。

**Comment by winderica** [comment]
嗯，是的。手头没有Android 9.0的机器，没法测试，我再找找相关的issue吧。

**Comment by linseedence** [comment]
好的麻烦你了大大，十分感谢🙏

**Comment by winderica** [comment]
打开应用之后，再输入以下命令试试：
```sh
frida -l hooks.js -U net.crigh.cgsport --no-pause
```
（即去掉`-f`这个flag）

**Comment by linseedence** [comment]
成功了大大！！！！非常感谢！！！

**Comment by winderica** [comment]
没事。先close了，还有问题的话请再open

**Comment by linseedence** [comment]
ok
